import Navbar from '@/components/navbar';
import './global.css';
import { Montserrat, Albert_Sans } from '@next/font/google';

export const metadata = {
    title: 'tnamdevnote',
    description: 'Generated by Next.js',
};

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-montserrat',
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={montserrat.variable}>
            <body className="mx-auto max-w-3xl px-6 md:px-10 xl:px-0 xl:max-w-5xl">
                <Navbar />
                <main>{children}</main>
            </body>
        </html>
    );
}
