import Navbar from '@/components/navbar';
import './global.css';

export const metadata = {
    title: 'tnamdevnote',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="mx-auto max-w-3xl px-6 md:px-10 xl:px-0 xl:max-w-5xl">
                <Navbar />
                <main>{children}</main>
            </body>
        </html>
    );
}
